### ISSUE TITLE
Run as root

### ISSUE THREAD

**Issue by duurent** [accetto/ubuntu-vnc-xfce-firefox-plus#4]
Is it possible to switch to root user like in the base image. Because password root or headless doesn't work. 
I can't get firefox to install on the base image so I would like this to be my starting image. 
However I need to install other applications as well.

**Comment by accetto** [comment]
You can always run any container as root by using the `--user` option like this:

```bash
docker run -d -P --user 0 accetto/ubuntu-vnc-xfce-firefox-plus
```
It's closer explained in [Wiki](https://github.com/accetto/ubuntu-vnc-xfce-firefox-plus/wiki/How-to#how-to-override-vnc-user).

If you don't need **noVNC**, you can find my newer image [accetto/xubuntu-vnc-firefox](https://hub.docker.com/r/accetto/xubuntu-vnc-firefox) even more suitable, because it supports **sudo** and you can easily install anything you need without needing **root**.  But you can also run it as **root**, of course.

Hope it helped.

Do not hesitate to re-open the issue, if you have more questions.

**Comment by duurent** [comment]
I can't get it to work, I just started with github and Docker so I am desperately trying to make it work.
Is is possible that you add an NoVNC version for accetto/xubuntu-vnc-chromium docker. (Since this one has sudo commands activated so there wouldn't be a need to access as root).

Or maybe you can help me in creating it for myself

The problem is that I am restricted in using a NoVNC container because of all the restriction with my connection. I need to access it over the internet.
